initial push for hierarcy based permissions
NatLibFi/melinda-record-import-api pull request #12
Opened 2019-08-21 07:33 UTC by natlibfi-jonollil

2019-08-21 12:31 UTC, ghost requested changes

2019-08-21 12:31 UTC, natlibfi-arlehiko commented on src/interfaces/utils.js
> +	const permintted = profile.groups.some(
Fix typo: `permintted` -> `permitted`

2019-08-21 12:31 UTC, natlibfi-arlehiko commented on src/interfaces/utils.js
> +export function hasPermission(type, command, profile, bgroups = []) {
Change parameter names to be more clear:

- *profile* -> **userGroups**
- *bgroups* -> **permittedGroups**

Also, it's unecessary to pass the whole profile object here. Passing `profile.auth.groups` is sufficient.

2019-08-21 12:31 UTC, natlibfi-arlehiko commented on src/interfaces/utils.js
> +	return profile.groups.some(group => bgroups.includes(group)) && permintted;
Optimization: Turn this the other way around nt reduce unnecessary array iteration if the boolean doesn't match:
`return permitted  && profile.groups.some(group => bgroups.includes(group))`

2019-08-22 05:58 UTC, ghost approved these changes

2019-08-23 12:17 UTC, ghost requested changes
Doesn't seem to check permission to use the `abort` operation of updateBlob?

2019-08-26 13:32 UTC, natlibfi-jonollil commented
> Doesn't seem to check permission to use the `abort` operation of updateBlob?

It needed `UPDATE` tier permissions to `ABORT`blob process. Fixed, updated tests and tested.

2019-08-28 06:00 UTC, ghost requested changes

2019-08-28 06:00 UTC, natlibfi-arlehiko commented on src/interfaces/utils.js
>  export function hasPermission(type, command, userGroups, permittedGroups = []) {
Make this more easier to read:
```js
const commandPermissions = permissions[type][command];

if (userGroups.includes('system')) {
  return true;

if (hasGroup(permittedGroups) === false) {
  return false;
}

if (commandPermissions.includes('all') || hasGroup(commandPermissions)) {
  return true;
}

function hasGroup(permitted) {
  return userGroups.some(g => permitted.includes(g));
}
```

2019-08-28 07:22 UTC, natlibfi-jonollil commented
https://github.com/NatLibFi/melinda-record-import-api/pull/14 merge first if possible?

2019-08-29 07:23 UTC, ghost approved these changes

2019-08-29 07:59 UTC, merged